trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: DockerCredentials

steps:
- task: Checkout@1

# Test variable values
- script: |
    echo "Testing Variables:"
    echo "DOCKER_USERNAME: $(DOCKER_USERNAME)"
    echo "DOCKER_PASSWORD: (hidden)"
  displayName: "Test variable values"

- task: Docker@2
  displayName: "Push Docker image"
  inputs:
    command: push
    containerRegistry:
      username: $(DOCKER_USERNAME)
      password: $(DOCKER_PASSWORD)
    repository: $(DOCKER_REPO)
    tags: |
      $(Build.BuildId)
