trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: DockerCredentials  # Link the variable group
- name: DOCKER_REGISTRY
  value: 'docker.io'
- name: DOCKER_REPO
  value: 'ssahblr/python-app'

steps:
# 1. Checkout code
- task: Checkout@1

# 2. Install Python dependencies and run tests
- script: |
    python -m pip install --upgrade pip
    pip install -r app/requirements.txt
    pytest app/ --junitxml=test-results.xml
  displayName: "Install dependencies and run tests"

# 3. Security scan using Trivy
- script: |
    curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -
    ./trivy image --exit-code 1 --severity HIGH $(DOCKER_REPO):latest || echo "No vulnerabilities"
  displayName: "Run Trivy security scan"

# 4. Build Docker image
- task: Docker@2
  displayName: "Build Docker image"
  inputs:
    command: build
    Dockerfile: Dockerfile
    tags: |
      $(DOCKER_REPO):$(Build.BuildId)

# 5. Push Docker image
- task: Docker@2
  displayName: "Push Docker image"
  inputs:
    command: push
    tags: |
      $(DOCKER_REPO):$(Build.BuildId)

# 6. Publish test results
- task: PublishTestResults@2
  displayName: "Publish test results"
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/test-results.xml'
