trigger:
- main

pool:
  name: 'mac-self'

variables:
- group: DockerCredentials
- name: DOCKER_REGISTRY
  value: 'docker.io'
- name: DOCKER_REPO
  value: 'ssahblr/python-app'

jobs:
- job: Build_and_Push
  displayName: "Build and Push Docker Image"
  steps:
  # 1. Checkout code
  # - task: Checkout@1
  #   displayName: "Checkout Code"

  # 2. Install Python manually
  - script: |
      echo "Installing Python..."
      brew install python3 || true
      python3 -m pip install --upgrade pip
      pip install flake8
    displayName: "Install Python and Linting Tool"

  # 3. Run Python linter
  - script: |
      echo "Running Python Linter..."
      flake8 app --count --select=E9,F63,F7,F82 --show-source --statistics
      flake8 app --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    displayName: "Run Python Linter"
    failOnStderr: true

  # 4. Download and prepare Trivy for security scanning
  - script: |
      echo "Downloading Trivy for security scanning..."
      curl -sSL https://github.com/aquasecurity/trivy/releases/download/v0.44.0/trivy_$(uname -s | tr '[:upper:]' '[:lower:]')_$(uname -m) -o trivy
      chmod +x trivy
    displayName: "Download Trivy"

  # 5. Run security scan with Trivy
  - script: |
      echo "Scanning Docker image for vulnerabilities..."
      ./trivy image $(DOCKER_REGISTRY)/$(DOCKER_REPO):$(Build.BuildId) || exit 1
    displayName: "Run Trivy Security Scan"
    failOnStderr: true

  # 6. Log in to the Docker registry
  - task: Docker@2
    displayName: "Log in to Docker registry"
    inputs:
      containerRegistry: 'Docker-service-conn'
      command: 'login'

  # 7. Build Docker image
  - task: Docker@2
    displayName: "Build Docker image"
    inputs:
      command: build
      Dockerfile: Dockerfile
      containerRegistry: 'Docker-service-conn'
      repository: $(DOCKER_REPO)
      tags: |
        $(Build.BuildId)

  # 8. Push Docker image
  - task: Docker@2
    displayName: "Push Docker image"
    inputs:
      command: push
      containerRegistry: 'Docker-service-conn'
      repository: $(DOCKER_REPO)
      tags: |
        $(Build.BuildId)
